import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [index("routes/home.tsx"),
    route("hro", "./hro.tsx"),
    route("mainpage","./mainpage.tsx"),
    route ("perfume", "./perfume.tsx"),
    route("jewery", "./jewery.tsx"),
    route("fragrance_story", "./fragrance_story.tsx"),
    route("jewelry_story","./jewelry_story.tsx"),
    route("jewelry_carousel","./jewelry_carousel.tsx"),
    route("shop_all","./shop_all.tsx"),
    route("new_product","./new_product.tsx"),
    route("cart","./cart.tsx"),
    route("login","./login.tsx"),
    route("register","./register.tsx"),
    route("profile", "./profile.tsx"),
    route("nav","./nav.tsx"),
    route("checkout", "./checkout.tsx"),  
    route("payment_success", "./payment_success.tsx"), 
    route("wishlist", "./wishlist.tsx"),  
    route("orders", "./orders.tsx"), 
    route("orderSuccess","./orderSuccess.tsx"),
    route("orderDetails/:id","./orderDetails.tsx"),
    route("footer","./footer.tsx"),
    route("forgotPassword/","./forgotPassword.tsx"),
    route("resetPassword/:uid/:token","./resetPassword.tsx"),

] satisfies RouteConfig;
